POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Trying to add user",
    "author": "The author",
    "url": "Link to blog",
    "likes": 112
}

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Interesting blog post",
    "author": "Author of blog",
    "url": "Link to interesting blog",
    "likes": 5
}
